### ISSUE TITLE
doesnt respond to any command idk why

### ISSUE THREAD

**Issue by zehelnehil** [luisgbr1el/TranslatorBOT#12]

**Comment by luisgbr1el** [comment]
Are you using **slash commands**?
Discord Bots doesn't supports "prefix bots" anymore since **August 31th, 2022**.

To use slash commands, just type `/`.
> Make sure Translator is in your server.

![image](https://user-images.githubusercontent.com/62726888/202787537-e17848e9-15d5-43a0-b7f4-cb248c781117.png)

If you type `/` and no one Translator's command appears. Please, go to https://translatorbot.gitbook.io/ and re-invite the bot.

**Comment by luisgbr1el** [comment]
> _No description provided._

Are you using **slash commands**?
Discord Bots doesn't supports "prefix bots" anymore since **August 31th, 2022**.

To use slash commands, just type `/`.
> Make sure Translator is in your server.

![image](https://user-images.githubusercontent.com/62726888/202787537-e17848e9-15d5-43a0-b7f4-cb248c781117.png)

If you type `/` and no one Translator's command appears. Please, go to https://translatorbot.gitbook.io/ and re-invite the bot.

**Comment by zehelnehil** [comment]
i use slash commands

**Comment by zehelnehil** [comment]
i was trying the code actually , your bot works great!

**Comment by luisgbr1el** [comment]
> i was trying the code actually , your bot works great!

Are you adding slash commands globally or in a specific server?

**Comment by zehelnehil** [comment]
im adding globally

**Comment by luisgbr1el** [comment]
> im adding globally

Can you send your `index.js` code, please?

**Comment by luisgbr1el** [comment]
Issue closed by inactivity.
